#define SYSCALL_ALLOW 1
#define SYSCALL_DENY 2
#define SYSCALL_SV 3

#define CPU_TIME_LIMIT_EXCEEDED 0x01
#define MEMORY_LIMIT_EXCEEDED 0x02
#define REAL_TIME_LIMIT_EXCEEDED 0x04
#define SECURITY_VIOLATION 0x08
